const createUser = () => {
    try {
        
    } catch (error) {
        console.log(error)
    }
}